name: Build & Release Workflow

on:
  push:
    tags: [ v* ]

jobs:
  release:
    name: Build, Test, & Release Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Codebase

      - uses: oven-sh/setup-bun@v1
        name: Setup Bun
        with:
          bun-version: v1.0.7

      - name: Install Dependencies
        run: bun install

      - name: Build Codebase
        run: bun run build

      - name: Test Codebase
        run: bun test --coverage

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          scope: "@4lch4"
          # Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

