name: Build & Release Workflow

on:
  push:
    tags: [ v* ]
  workflow_dispatch: {}

jobs:
  release:
    name: Build, Test, & Release Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Codebase

      - uses: oven-sh/setup-bun@v1
        name: Setup Bun
        with:
          bun-version: v1.0.7

      - name: Install Dependencies
        run: bun install

      - name: Build Codebase
        run: bun run build

      - name: Test Codebase
        run: bun test --coverage

      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

